/*
 * Copyright (c) 2021-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using cloud.charging.open.protocols.ISO15118.EXI.SourceGenerator.Grammar;

namespace cloud.charging.open.protocols.ISO15118.EXI.SourceGenerator.Emit
{
    /// <summary>
    /// The Kotlin JSON-LD (de)serializer — the same pass as <see cref="CSharpJsonEmitter"/>, held to
    /// the same documents.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>What "the same" means here.</b> Not the same code shape: Kotlin properties are camelCase
    /// where C#'s are PascalCase, so this emitter reads <c>msg.eVCCID</c> where the C# one reads
    /// <c>msg.EVCCID</c>. The JSON property is <c>evccid</c> in both, because <see cref="JsonNaming"/>
    /// derives it from the <em>plan's</em> field name rather than from either language's spelling.
    /// That is the whole reason the naming rule sits in the language-neutral layer — three back ends
    /// with three identifier conventions have to agree on one document.
    /// </para>
    /// <para>
    /// The agreement is checked, not assumed: <c>JsonLd.documents.json</c> holds every vector's JSON
    /// form as C# produces it, and the Kotlin tests compare character for character. The round trip
    /// alone could not — rename a property in both directions and it stays green.
    /// </para>
    /// </remarks>
    internal sealed class KotlinJsonEmitter
    {

        private readonly SchemaPlan _plan;
        private readonly string _package;
        private readonly string _object;
        private readonly StringBuilder _sb = new();

        private readonly List<SequencePlan> _records = new();
        private readonly Dictionary<string, SequencePlan> _byName = new(StringComparer.Ordinal);


        private KotlinJsonEmitter(SchemaPlan plan, string package, string codecObject)
        {
            _plan    = plan;
            _package = package;
            _object  = codecObject + "Json";

            var seen = new HashSet<string>(StringComparer.Ordinal);

            void Add(SequencePlan sp)
            {
                if (!seen.Add(sp.RecordName)) return;
                _byName[sp.RecordName] = sp;
                if (!sp.IsAbstract) _records.Add(sp);
            }

            foreach (var sp in plan.ComplexTypes.Values) Add(sp);
            foreach (var g in plan.GlobalElements)       Add(g.Body);
        }


        public static IReadOnlyList<GeneratedFile> Emit(SchemaPlan plan, string package, string codecObject) =>
            new KotlinJsonEmitter(plan, package, codecObject).Run();


        private IReadOnlyList<GeneratedFile> Run()
        {

            var documents = new HashSet<string>(_plan.GlobalElements.Select(g => g.Body.RecordName),
                                                StringComparer.Ordinal);

            var files = new List<GeneratedFile>();

            foreach (var sp in _records)
                files.Add(Part(sp.RecordName, () => {
                    EmitSerializer(sp, documents.Contains(sp.RecordName));
                    EmitParser(sp);
                }));

            foreach (var name in _plan.OpaqueTypes)
                files.Add(Part(name, () => EmitOpaque(name)));

            files.Add(Part(_object, EmitDispatchers));

            return files;
        }


        /// <summary>One generated file. Kotlin has no partial objects, so the per-type halves are
        /// top-level functions next to the type — exactly what the codec emitter does.</summary>
        private GeneratedFile Part(string name, Action emit)
        {
            _sb.Clear();
            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Kotlin back end). Do not edit by hand.");
            _sb.AppendLine();
            _sb.Append("package ").AppendLine(_package);
            _sb.AppendLine();
            _sb.AppendLine("import cloud.charging.v2g.exi.JsonArray");
            _sb.AppendLine("import cloud.charging.v2g.exi.JsonLdException");
            _sb.AppendLine("import cloud.charging.v2g.exi.JsonObject");
            _sb.AppendLine("import cloud.charging.v2g.exi.JsonPrimitives");
            _sb.AppendLine("import cloud.charging.v2g.exi.JsonValue");
            _sb.AppendLine();

            emit();

            return new GeneratedFile(name + ".Json.kt", _sb.ToString());
        }


        private void EmitDispatchers()
        {
            _sb.Append("object ").Append(_object).AppendLine(" {");
            _sb.AppendLine();
            _sb.AppendLine("    /** The vocabulary these messages are written in: the XSD target namespace. */");
            _sb.Append("    const val CONTEXT = \"").Append(JsonNaming.Context(_plan.TargetNamespace)).AppendLine("\"");
            _sb.AppendLine();

            // Dispatch is on the RUNTIME type, and branches are ordered most-derived-first for the
            // reason every other type dispatch in this back end is: Kotlin's `is` matches subtypes,
            // so a base-first order would serialise every derived value as its base and silently drop
            // the fields the derived type added.
            _sb.AppendLine("    /** The JSON-LD form of any generated message or type. */");
            _sb.AppendLine("    fun toJson(value: Any): JsonObject =");
            _sb.AppendLine("        when (value) {");

            foreach (var sp in _records.OrderByDescending(Depth).ThenBy(sp => sp.RecordName, StringComparer.Ordinal))
                _sb.Append("            is ").Append(Ident(sp.RecordName)).Append(" -> toJson")
                   .Append(Ident(sp.RecordName)).AppendLine("(value)");

            foreach (var name in _plan.OpaqueTypes)
                _sb.Append("            is ").Append(Ident(name)).Append(" -> toJson")
                   .Append(Ident(name)).AppendLine("(value)");

            _sb.AppendLine();
            _sb.AppendLine("            else -> throw JsonLdException(");
            _sb.AppendLine("                \"${value::class.simpleName} is not a type of this message set.\")");
            _sb.AppendLine("        }");
            _sb.AppendLine();

            _sb.AppendLine("    /** Reads any generated message or type back, by its `@type`. */");
            _sb.AppendLine("    fun parseJson(node: JsonValue?, what: String = \"the document\"): Any {");
            _sb.AppendLine();
            _sb.AppendLine("        val json = JsonPrimitives.obj(node, what)");
            _sb.AppendLine();
            _sb.AppendLine("        return when (val type = JsonPrimitives.typeTag(json, what)) {");

            foreach (var sp in _records)
                _sb.Append("            \"").Append(KStr(sp.RecordName)).Append("\" -> parseJson")
                   .Append(Ident(sp.RecordName)).AppendLine("(json)");

            foreach (var name in _plan.OpaqueTypes)
                _sb.Append("            \"").Append(KStr(name)).Append("\" -> parseJson")
                   .Append(Ident(name)).AppendLine("(json)");

            _sb.AppendLine();
            _sb.AppendLine("            else -> throw JsonLdException(");
            _sb.AppendLine("                \"$what has @type '$type', which is not a type of this message set.\")");
            _sb.AppendLine("        }");
            _sb.AppendLine("    }");
            _sb.AppendLine("}");
        }


        private int Depth(SequencePlan sp)
        {
            var depth = 0;
            var current = sp;
            while (current.BaseRecordName is not null && _byName.TryGetValue(current.BaseRecordName, out var next))
            {
                depth++;
                current = next;
            }
            return depth;
        }


        // -----------------------------------------------------------------------
        //  Per-type
        // -----------------------------------------------------------------------

        private void EmitSerializer(SequencePlan sp, bool isDocument)
        {
            JsonNaming.RequireDistinct(sp.RecordName, FieldNames(sp));

            _sb.Append("internal fun toJson").Append(Ident(sp.RecordName))
               .Append("(value: ").Append(Ident(sp.RecordName)).AppendLine("): JsonObject {");
            _sb.AppendLine();
            _sb.AppendLine("    val json = JsonObject()");
            _sb.AppendLine();

            if (isDocument)
                _sb.Append("    json[\"@context\"] = JsonValue.of(").Append(_object).AppendLine(".CONTEXT)");

            _sb.Append("    json[\"@type\"] = JsonValue.of(\"").Append(KStr(sp.RecordName)).AppendLine("\")");
            _sb.AppendLine();

            if (sp.Attributes is not null)
                foreach (var a in sp.Attributes)
                    EmitWrite(a.FieldName, a.Type, a.Value, optional: !a.Required);

            if (sp.SimpleContent is not null)
                EmitWrite(SimpleContentField, sp.SimpleContentType!, sp.SimpleContent, optional: false);

            foreach (var c in sp.Children)
            {
                if (c.Value is ValueEncoding.InlineChoice ic)
                {
                    foreach (var m in ic.Members)
                        EmitWrite(m.FieldName, m.Type, m.Value, optional: true);
                    continue;
                }

                if (c.Shape == ChildShape.BoundedRepeating)
                {
                    var array = "_" + JsonNaming.Property(c.FieldName);
                    _sb.Append("    val ").Append(array).AppendLine(" = JsonArray()");
                    _sb.Append("    for (item in value.").Append(Prop(c.FieldName)).AppendLine(")");
                    _sb.Append("        ").Append(array).Append(".add(")
                       .Append(Serialize("item", c.Type, c.Value)).AppendLine(")");
                    _sb.Append("    json[\"").Append(JsonNaming.Property(c.FieldName)).Append("\"] = ")
                       .AppendLine(array);
                    _sb.AppendLine();
                    continue;
                }

                EmitWrite(c.FieldName, c.Type, c.Value, optional: c.Shape == ChildShape.OptionalSingle);
            }

            _sb.AppendLine("    return json");
            _sb.AppendLine("}");
            _sb.AppendLine();
        }


        private void EmitWrite(string field, TypeRef type, ValueEncoding value, bool optional)
        {
            var property = JsonNaming.Property(field);

            if (!optional)
            {
                _sb.Append("    json[\"").Append(property).Append("\"] = ")
                   .AppendLine(Serialize("value." + Prop(field), type, value));
                return;
            }

            // `?.let` rather than an `if` with a smart cast: an overridden `open val` has no smart
            // cast in Kotlin, and half the generated types override their base's properties.
            // Absent properties are omitted, never written as null — a JSON-LD document lists what
            // is there.
            _sb.Append("    value.").Append(Prop(field)).Append("?.let { json[\"").Append(property)
               .Append("\"] = ").Append(Serialize("it", type, value)).AppendLine(" }");
            _sb.AppendLine();
        }


        private void EmitParser(SequencePlan sp)
        {
            _sb.Append("internal fun parseJson").Append(Ident(sp.RecordName))
               .Append("(json: JsonObject): ").Append(Ident(sp.RecordName)).AppendLine(" =");

            var arguments = new List<string>();

            if (sp.Attributes is not null)
                foreach (var a in sp.Attributes)
                    arguments.Add(Read(sp.RecordName, a.FieldName, a.Type, a.Value, optional: !a.Required));

            if (sp.SimpleContent is not null)
                arguments.Add(Read(sp.RecordName, SimpleContentField, sp.SimpleContentType!,
                                   sp.SimpleContent, optional: false));

            foreach (var c in sp.Children)
            {
                if (c.Value is ValueEncoding.InlineChoice ic)
                {
                    foreach (var m in ic.Members)
                        arguments.Add(Read(sp.RecordName, m.FieldName, m.Type, m.Value, optional: true));
                    continue;
                }

                if (c.Shape == ChildShape.BoundedRepeating)
                {
                    arguments.Add(ReadList(sp.RecordName, c));
                    continue;
                }

                arguments.Add(Read(sp.RecordName, c.FieldName, c.Type, c.Value,
                                   optional: c.Shape == ChildShape.OptionalSingle));
            }

            if (arguments.Count == 0)
            {
                _sb.Append("    ").Append(Ident(sp.RecordName)).AppendLine("()");
                _sb.AppendLine();
                return;
            }

            _sb.Append("    ").Append(Ident(sp.RecordName)).AppendLine("(");
            for (var i = 0; i < arguments.Count; i++)
            {
                _sb.Append("        ").Append(arguments[i]);
                _sb.AppendLine(i + 1 < arguments.Count ? "," : "");
            }
            _sb.AppendLine("    )");
            _sb.AppendLine();
        }


        /// <summary>An element in an opaque namespace (XMLDSig): no content on the wire, none here.</summary>
        private void EmitOpaque(string name)
        {
            _sb.Append("internal fun toJson").Append(Ident(name)).Append("(value: ").Append(Ident(name))
               .AppendLine("): JsonObject {");
            _sb.AppendLine();
            _sb.AppendLine("    val json = JsonObject()");
            _sb.Append("    json[\"@type\"] = JsonValue.of(\"").Append(KStr(name)).AppendLine("\")");
            _sb.AppendLine("    return json");
            _sb.AppendLine("}");
            _sb.AppendLine();
            _sb.Append("internal fun parseJson").Append(Ident(name)).Append("(json: JsonObject): ")
               .Append(Ident(name)).AppendLine(" =");
            _sb.Append("    ").Append(Ident(name)).AppendLine("()");
            _sb.AppendLine();
        }


        // -----------------------------------------------------------------------
        //  Values
        // -----------------------------------------------------------------------

        private enum Kind { Record, Enumeration, Primitive }

        private static Kind KindOf(TypeRef type, ValueEncoding value) => value switch
        {
            ValueEncoding.EnumIndex          => Kind.Enumeration,
            ValueEncoding.ComplexRef         => Kind.Record,
            ValueEncoding.OpaqueElement      => Kind.Record,
            ValueEncoding.SubstitutionChoice => Kind.Record,
            _ => type is TypeRef.Named ? Kind.Record : Kind.Primitive,
        };


        private string Serialize(string access, TypeRef type, ValueEncoding value) =>
            KindOf(type, value) switch
            {
                Kind.Record      => $"{_object}.toJson({access})",
                Kind.Enumeration => $"JsonValue.of({access}.name)",
                _                => SerializePrimitive(access, ((TypeRef.Primitive) type).Kind),
            };

        private static string SerializePrimitive(string access, PrimitiveKind kind) => kind switch
        {
            PrimitiveKind.Int64  => $"JsonValue.of(JsonPrimitives.fromInt64({access}))",
            PrimitiveKind.UInt64 => $"JsonValue.of(JsonPrimitives.fromUInt64({access}))",
            PrimitiveKind.Binary => $"JsonValue.of(JsonPrimitives.toHex({access}))",
            _                    => $"JsonValue.of({access})",
        };


        private string Read(string owner, string field, TypeRef type, ValueEncoding value, bool optional)
        {
            var property = JsonNaming.Property(field);

            return optional
                       ? $"JsonPrimitives.optional(json, \"{property}\")?.let {{ "
                       + $"{ReadFrom("it", owner, property, type, value)} }}"
                       : ReadFrom($"JsonPrimitives.required(json, \"{property}\", \"{KStr(owner)}\")",
                                  owner, property, type, value);
        }


        private string ReadFrom(string node, string owner, string property, TypeRef type, ValueEncoding value) =>
            KindOf(type, value) switch
            {
                Kind.Record      => $"JsonPrimitives.cast<{Ident(Type(type))}>("
                                  + $"{_object}.parseJson({node}, \"{KStr(owner)}.{property}\"), "
                                  + $"\"{property}\", \"{KStr(owner)}\")",
                Kind.Enumeration => $"JsonPrimitives.enumeration({node}, \"{property}\", "
                                  + $"\"{KStr(owner)}\", {Ident(Type(type))}.values())",
                _                => ReadPrimitive(node, owner, property, ((TypeRef.Primitive) type).Kind),
            };

        private static string ReadPrimitive(string node, string owner, string property, PrimitiveKind kind)
        {
            var method = kind switch
            {
                PrimitiveKind.Bool   => "bool",
                PrimitiveKind.Int8   => "int8",
                PrimitiveKind.Int16  => "int16",
                PrimitiveKind.Int32  => "int32",
                PrimitiveKind.Int64  => "int64",
                PrimitiveKind.UInt8  => "uint8",
                PrimitiveKind.UInt16 => "uint16",
                PrimitiveKind.UInt32 => "uint32",
                PrimitiveKind.UInt64 => "uint64",
                PrimitiveKind.String => "stringValue",
                PrimitiveKind.Binary => "binary",
                _ => throw new NotSupportedException($"Kotlin JSON back end: primitive '{kind}'."),
            };

            return $"JsonPrimitives.{method}({node}, \"{property}\", \"{KStr(owner)}\")";
        }


        /// <summary>A repeating child. A list that may be empty tolerates the property being absent;
        /// one that requires items demands it.</summary>
        private string ReadList(string owner, ChildPlan c)
        {
            var property = JsonNaming.Property(c.FieldName);
            var element  = ReadFrom("it", owner, property, c.Type, c.Value);

            return c.ListMin > 0
                       ? $"JsonPrimitives.array(json, \"{property}\", \"{KStr(owner)}\").asList().map {{ {element} }}"
                       : $"(JsonPrimitives.optional(json, \"{property}\") as? JsonArray)"
                       + $"?.asList()?.map {{ {element} }} ?: emptyList()";
        }


        private static IEnumerable<string> FieldNames(SequencePlan sp)
        {
            if (sp.Attributes is not null)
                foreach (var a in sp.Attributes)
                    yield return a.FieldName;

            if (sp.SimpleContent is not null)
                yield return SimpleContentField;

            foreach (var c in sp.Children)
            {
                if (c.Value is ValueEncoding.InlineChoice ic)
                {
                    foreach (var m in ic.Members)
                        yield return m.FieldName;
                    continue;
                }
                yield return c.FieldName;
            }
        }


        // -----------------------------------------------------------------------
        //  Kotlin spelling
        // -----------------------------------------------------------------------
        //
        //  Deliberate copies of KotlinCodecEmitter's private helpers rather than a shared layer: the
        //  two emitters have to agree, and a disagreement is not silent — it produces Kotlin that
        //  does not compile, which is the cheapest possible way to find out.

        private const string SimpleContentField = "Value";

        private static readonly HashSet<string> KotlinKeywords = new(StringComparer.Ordinal)
        {
            "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in",
            "interface", "is", "null", "object", "package", "return", "super", "this", "throw",
            "true", "try", "typealias", "typeof", "val", "var", "when", "while",
        };

        private static string KStr(string s) =>
            s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("$", "\\$");

        private static string Camel(string pascal) =>
            pascal.Length == 0 ? pascal : char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);

        private static string Prop(string pascal) => Ident(Camel(pascal));

        private static string Ident(string name)
        {
            if (string.IsNullOrEmpty(name)) return "_";

            var sb = new StringBuilder(name.Length);
            foreach (var c in name)
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');

            var identifier = sb.ToString();
            return KotlinKeywords.Contains(identifier) ? "`" + identifier + "`" : identifier;
        }

        private static string Type(TypeRef t) => t switch
        {
            TypeRef.Primitive p => p.Kind switch
            {
                PrimitiveKind.Bool   => "Boolean",
                PrimitiveKind.Int8   => "Byte",
                PrimitiveKind.Int16  => "Short",
                PrimitiveKind.Int32  => "Int",
                PrimitiveKind.Int64  => "Long",
                PrimitiveKind.UInt8  => "UByte",
                PrimitiveKind.UInt16 => "UShort",
                PrimitiveKind.UInt32 => "UInt",
                PrimitiveKind.UInt64 => "ULong",
                PrimitiveKind.String => "String",
                PrimitiveKind.Binary => "ByteArray",
                _ => throw new NotSupportedException($"Kotlin JSON back end: primitive {p.Kind}."),
            },
            TypeRef.Named n => n.Name,
            _ => throw new NotSupportedException("Kotlin JSON back end: untyped child."),
        };

    }
}
