/*
 * Copyright (c) 2021-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using cloud.charging.open.protocols.ISO15118.EXI.SourceGenerator.Grammar;

namespace cloud.charging.open.protocols.ISO15118.EXI.SourceGenerator.Emit
{
    /// <summary>
    /// The Swift JSON-LD (de)serializer — the third back end of the same pass, held to the same
    /// documents.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Two shapes differ from C# and Kotlin, and neither changes a character of the output.
    /// </para>
    /// <list type="bullet">
    ///   <item><b>Everything throws.</b> Swift has no unchecked exceptions, so serializing throws as
    ///         well as parsing — <c>toJSON</c> ends in a dispatch that can fail on a type from
    ///         another message set, and that has to be declared all the way up.</item>
    ///   <item><b>Initialisers take labels.</b> C# and Kotlin build a record positionally; Swift
    ///         names every argument, so the parser emits <c>X(header: …, evccid: …)</c>. The labels
    ///         are the Swift property names, which are <em>not</em> the JSON property names — one is
    ///         <c>eVCCID</c>, the other <c>evccid</c>. Keeping them apart is the whole reason
    ///         <see cref="JsonNaming"/> derives from the plan rather than from a language.</item>
    /// </list>
    /// </remarks>
    internal sealed class SwiftJsonEmitter
    {

        private readonly SchemaPlan _plan;
        private readonly string _enum;
        private readonly StringBuilder _sb = new();

        private readonly List<SequencePlan> _records = new();
        private readonly Dictionary<string, SequencePlan> _byName = new(StringComparer.Ordinal);


        private SwiftJsonEmitter(SchemaPlan plan, string codecEnum)
        {
            _plan = plan;
            _enum = codecEnum + "Json";

            var seen = new HashSet<string>(StringComparer.Ordinal);

            void Add(SequencePlan sp)
            {
                if (!seen.Add(sp.RecordName)) return;
                _byName[sp.RecordName] = sp;
                if (!sp.IsAbstract) _records.Add(sp);
            }

            foreach (var sp in plan.ComplexTypes.Values) Add(sp);
            foreach (var g in plan.GlobalElements)       Add(g.Body);
        }


        public static IReadOnlyList<GeneratedFile> Emit(SchemaPlan plan, string module, string codecEnum) =>
            new SwiftJsonEmitter(plan, codecEnum).Run();


        private IReadOnlyList<GeneratedFile> Run()
        {

            var documents = new HashSet<string>(_plan.GlobalElements.Select(g => g.Body.RecordName),
                                                StringComparer.Ordinal);

            var files = new List<GeneratedFile>();

            foreach (var sp in _records)
                files.Add(Part(sp.RecordName, () => {
                    EmitSerializer(sp, documents.Contains(sp.RecordName));
                    EmitParser(sp);
                }));

            foreach (var name in _plan.OpaqueTypes)
                files.Add(Part(name, () => EmitOpaque(name)));

            files.Add(Part(_enum, EmitDispatchers));

            return files;
        }


        private GeneratedFile Part(string name, Action emit)
        {
            _sb.Clear();
            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("// Generated by Vanaheimr.V2G.Exi.SourceGenerator (Swift back end). Do not edit by hand.");
            _sb.AppendLine();
            _sb.AppendLine("import ExiRuntime");
            _sb.AppendLine();

            emit();

            return new GeneratedFile(name + ".Json.swift", _sb.ToString());
        }


        private void EmitDispatchers()
        {
            _sb.Append("public enum ").Append(_enum).AppendLine(" {");
            _sb.AppendLine();
            _sb.AppendLine("    /// The vocabulary these messages are written in: the XSD target namespace.");
            _sb.Append("    public static let context = \"").Append(JsonNaming.Context(_plan.TargetNamespace))
               .AppendLine("\"");
            _sb.AppendLine();

            // Dispatch is on the RUNTIME type, and branches are ordered most-derived-first: Swift's
            // `as` matches superclasses too, so a base-first order would serialise every derived
            // value as its base and silently drop the fields the derived type added.
            _sb.AppendLine("    /// The JSON-LD form of any generated message or type.");
            _sb.AppendLine("    public static func toJSON(_ value: Any) throws -> JsonObject {");
            _sb.AppendLine();
            _sb.AppendLine("        switch value {");

            foreach (var sp in _records.OrderByDescending(Depth).ThenBy(sp => sp.RecordName, StringComparer.Ordinal))
                _sb.Append("        case let v as ").Append(Ident(sp.RecordName)).Append(": return try toJSON")
                   .Append(Ident(sp.RecordName)).AppendLine("(v)");

            foreach (var name in _plan.OpaqueTypes)
                _sb.Append("        case let v as ").Append(Ident(name)).Append(": return toJSON")
                   .Append(Ident(name)).AppendLine("(v)");

            _sb.AppendLine();
            _sb.AppendLine("        default: throw JsonLdError(");
            _sb.AppendLine("                     \"\\(type(of: value)) is not a type of this message set.\")");
            _sb.AppendLine("        }");
            _sb.AppendLine("    }");
            _sb.AppendLine();

            _sb.AppendLine("    /// Reads any generated message or type back, by its `@type`.");
            _sb.AppendLine("    public static func parseJSON(_ node: JsonValue?, _ what: String = \"the document\") throws -> Any {");
            _sb.AppendLine();
            _sb.AppendLine("        let json = try JsonPrimitives.object(node, what)");
            _sb.AppendLine();
            _sb.AppendLine("        switch try JsonPrimitives.typeTag(json, what) {");

            foreach (var sp in _records)
                _sb.Append("        case \"").Append(SStr(sp.RecordName)).Append("\": return try parseJSON")
                   .Append(Ident(sp.RecordName)).AppendLine("(json)");

            foreach (var name in _plan.OpaqueTypes)
                _sb.Append("        case \"").Append(SStr(name)).Append("\": return parseJSON")
                   .Append(Ident(name)).AppendLine("(json)");

            _sb.AppendLine();
            _sb.AppendLine("        case let other: throw JsonLdError(");
            _sb.AppendLine("                            \"\\(what) has @type '\\(other)', which is not a type of this message set.\")");
            _sb.AppendLine("        }");
            _sb.AppendLine("    }");
            _sb.AppendLine("}");
        }


        private int Depth(SequencePlan sp)
        {
            var depth = 0;
            var current = sp;
            while (current.BaseRecordName is not null && _byName.TryGetValue(current.BaseRecordName, out var next))
            {
                depth++;
                current = next;
            }
            return depth;
        }


        // -----------------------------------------------------------------------
        //  Per-type
        // -----------------------------------------------------------------------

        private void EmitSerializer(SequencePlan sp, bool isDocument)
        {
            JsonNaming.RequireDistinct(sp.RecordName, FieldNames(sp));

            _sb.Append("internal func toJSON").Append(Ident(sp.RecordName))
               .Append("(_ value: ").Append(Ident(sp.RecordName)).AppendLine(") throws -> JsonObject {");
            _sb.AppendLine();
            _sb.AppendLine("    let json = JsonObject()");
            _sb.AppendLine();

            if (isDocument)
                _sb.Append("    json[\"@context\"] = JsonValue.of(").Append(_enum).AppendLine(".context)");

            _sb.Append("    json[\"@type\"] = JsonValue.of(\"").Append(SStr(sp.RecordName)).AppendLine("\")");
            _sb.AppendLine();

            if (sp.Attributes is not null)
                foreach (var a in sp.Attributes)
                    EmitWrite(a.FieldName, a.Type, a.Value, optional: !a.Required);

            if (sp.SimpleContent is not null)
                EmitWrite(SimpleContentField, sp.SimpleContentType!, sp.SimpleContent, optional: false);

            foreach (var c in sp.Children)
            {
                if (c.Value is ValueEncoding.InlineChoice ic)
                {
                    foreach (var m in ic.Members)
                        EmitWrite(m.FieldName, m.Type, m.Value, optional: true);
                    continue;
                }

                if (c.Shape == ChildShape.BoundedRepeating)
                {
                    var array = "_" + JsonNaming.Property(c.FieldName);
                    _sb.Append("    let ").Append(array).AppendLine(" = JsonArray()");
                    _sb.Append("    for item in value.").Append(Prop(c.FieldName)).AppendLine(" {");
                    _sb.Append("        ").Append(array).Append(".add(")
                       .Append(Serialize("item", c.Type, c.Value)).AppendLine(")");
                    _sb.AppendLine("    }");
                    _sb.Append("    json[\"").Append(JsonNaming.Property(c.FieldName)).Append("\"] = ")
                       .AppendLine(array);
                    _sb.AppendLine();
                    continue;
                }

                EmitWrite(c.FieldName, c.Type, c.Value, optional: c.Shape == ChildShape.OptionalSingle);
            }

            _sb.AppendLine("    return json");
            _sb.AppendLine("}");
            _sb.AppendLine();
        }


        private void EmitWrite(string field, TypeRef type, ValueEncoding value, bool optional)
        {
            var property = JsonNaming.Property(field);

            if (!optional)
            {
                _sb.Append("    json[\"").Append(property).Append("\"] = ")
                   .AppendLine(Serialize("value." + Prop(field), type, value));
                return;
            }

            // Absent properties are omitted, never written as null — a JSON-LD document lists what
            // is there.
            _sb.Append("    if let v = value.").Append(Prop(field)).AppendLine(" {");
            _sb.Append("        json[\"").Append(property).Append("\"] = ")
               .AppendLine(Serialize("v", type, value));
            _sb.AppendLine("    }");
            _sb.AppendLine();
        }


        private void EmitParser(SequencePlan sp)
        {
            _sb.Append("internal func parseJSON").Append(Ident(sp.RecordName))
               .Append("(_ json: JsonObject) throws -> ").Append(Ident(sp.RecordName)).AppendLine(" {");
            _sb.AppendLine();

            var arguments = new List<string>();

            void Argument(string field, TypeRef type, ValueEncoding value, bool optional) =>
                arguments.Add(Prop(field) + ": " + Read(sp.RecordName, field, type, value, optional));

            if (sp.Attributes is not null)
                foreach (var a in sp.Attributes)
                    Argument(a.FieldName, a.Type, a.Value, !a.Required);

            if (sp.SimpleContent is not null)
                Argument(SimpleContentField, sp.SimpleContentType!, sp.SimpleContent, false);

            foreach (var c in sp.Children)
            {
                if (c.Value is ValueEncoding.InlineChoice ic)
                {
                    foreach (var m in ic.Members)
                        Argument(m.FieldName, m.Type, m.Value, true);
                    continue;
                }

                if (c.Shape == ChildShape.BoundedRepeating)
                {
                    arguments.Add(Prop(c.FieldName) + ": " + ReadList(sp.RecordName, c));
                    continue;
                }

                Argument(c.FieldName, c.Type, c.Value, c.Shape == ChildShape.OptionalSingle);
            }

            if (arguments.Count == 0)
            {
                _sb.Append("    return ").Append(Ident(sp.RecordName)).AppendLine("()");
                _sb.AppendLine("}");
                _sb.AppendLine();
                return;
            }

            _sb.Append("    return ").Append(Ident(sp.RecordName)).AppendLine("(");
            for (var i = 0; i < arguments.Count; i++)
            {
                _sb.Append("        ").Append(arguments[i]);
                _sb.AppendLine(i + 1 < arguments.Count ? "," : "");
            }
            _sb.AppendLine("    )");
            _sb.AppendLine("}");
            _sb.AppendLine();
        }


        /// <summary>An element in an opaque namespace (XMLDSig): no content on the wire, none here.</summary>
        private void EmitOpaque(string name)
        {
            _sb.Append("internal func toJSON").Append(Ident(name)).Append("(_ value: ").Append(Ident(name))
               .AppendLine(") -> JsonObject {");
            _sb.AppendLine();
            _sb.AppendLine("    let json = JsonObject()");
            _sb.Append("    json[\"@type\"] = JsonValue.of(\"").Append(SStr(name)).AppendLine("\")");
            _sb.AppendLine("    return json");
            _sb.AppendLine("}");
            _sb.AppendLine();
            _sb.Append("internal func parseJSON").Append(Ident(name)).Append("(_ json: JsonObject) -> ")
               .Append(Ident(name)).AppendLine(" {");
            _sb.Append("    return ").Append(Ident(name)).AppendLine("()");
            _sb.AppendLine("}");
            _sb.AppendLine();
        }


        // -----------------------------------------------------------------------
        //  Values
        // -----------------------------------------------------------------------

        private enum Kind { Record, Enumeration, Primitive }

        private static Kind KindOf(TypeRef type, ValueEncoding value) => value switch
        {
            ValueEncoding.EnumIndex          => Kind.Enumeration,
            ValueEncoding.ComplexRef         => Kind.Record,
            ValueEncoding.OpaqueElement      => Kind.Record,
            ValueEncoding.SubstitutionChoice => Kind.Record,
            _ => type is TypeRef.Named ? Kind.Record : Kind.Primitive,
        };


        private string Serialize(string access, TypeRef type, ValueEncoding value) =>
            KindOf(type, value) switch
            {
                Kind.Record      => $"try {_enum}.toJSON({access})",
                Kind.Enumeration => $"JsonValue.of(JsonPrimitives.fromEnumeration({access}))",
                _                => SerializePrimitive(access, ((TypeRef.Primitive) type).Kind),
            };

        private static string SerializePrimitive(string access, PrimitiveKind kind) => kind switch
        {
            PrimitiveKind.Int64  => $"JsonValue.of(JsonPrimitives.fromInt64({access}))",
            PrimitiveKind.UInt64 => $"JsonValue.of(JsonPrimitives.fromUInt64({access}))",
            PrimitiveKind.Binary => $"JsonValue.of(JsonPrimitives.toHex({access}))",
            _                    => $"JsonValue.of({access})",
        };


        private string Read(string owner, string field, TypeRef type, ValueEncoding value, bool optional)
        {
            var property = JsonNaming.Property(field);

            // `map` over the optional keeps this an expression, which is what an initialiser argument
            // has to be; `try` outside it covers the closure, since Swift propagates a rethrow.
            return optional
                       ? $"try JsonPrimitives.optional(json, \"{property}\").map {{ "
                       + $"{ReadFrom("$0", owner, property, type, value)} }}"
                       : ReadFrom($"try JsonPrimitives.required(json, \"{property}\", \"{SStr(owner)}\")",
                                  owner, property, type, value);
        }


        private string ReadFrom(string node, string owner, string property, TypeRef type, ValueEncoding value) =>
            KindOf(type, value) switch
            {
                Kind.Record      => $"try JsonPrimitives.cast({_enum}.parseJSON({node}, "
                                  + $"\"{SStr(owner)}.{property}\"), \"{property}\", \"{SStr(owner)}\") "
                                  + $"as {Ident(Type(type))}",
                Kind.Enumeration => $"try JsonPrimitives.enumeration({node}, \"{property}\", "
                                  + $"\"{SStr(owner)}\", {Ident(Type(type))}.self)",
                _                => ReadPrimitive(node, owner, property, ((TypeRef.Primitive) type).Kind),
            };

        private static string ReadPrimitive(string node, string owner, string property, PrimitiveKind kind)
        {
            var method = kind switch
            {
                PrimitiveKind.Bool   => "bool",
                PrimitiveKind.Int8   => "int8",
                PrimitiveKind.Int16  => "int16",
                PrimitiveKind.Int32  => "int32",
                PrimitiveKind.Int64  => "int64",
                PrimitiveKind.UInt8  => "uint8",
                PrimitiveKind.UInt16 => "uint16",
                PrimitiveKind.UInt32 => "uint32",
                PrimitiveKind.UInt64 => "uint64",
                PrimitiveKind.String => "stringValue",
                PrimitiveKind.Binary => "binary",
                _ => throw new NotSupportedException($"Swift JSON back end: primitive '{kind}'."),
            };

            return $"try JsonPrimitives.{method}({node}, \"{property}\", \"{SStr(owner)}\")";
        }


        private string ReadList(string owner, ChildPlan c)
        {
            var property = JsonNaming.Property(c.FieldName);
            var element  = ReadFrom("$0", owner, property, c.Type, c.Value);

            return c.ListMin > 0
                       ? $"try JsonPrimitives.array(json, \"{property}\", \"{SStr(owner)}\")"
                       + $".asList.map {{ {element} }}"
                       : $"try (JsonPrimitives.optional(json, \"{property}\") as? JsonArray)"
                       + $"?.asList.map {{ {element} }} ?? []";
        }


        private static IEnumerable<string> FieldNames(SequencePlan sp)
        {
            if (sp.Attributes is not null)
                foreach (var a in sp.Attributes)
                    yield return a.FieldName;

            if (sp.SimpleContent is not null)
                yield return SimpleContentField;

            foreach (var c in sp.Children)
            {
                if (c.Value is ValueEncoding.InlineChoice ic)
                {
                    foreach (var m in ic.Members)
                        yield return m.FieldName;
                    continue;
                }
                yield return c.FieldName;
            }
        }


        // -----------------------------------------------------------------------
        //  Swift spelling
        // -----------------------------------------------------------------------
        //
        //  Copies of SwiftCodecEmitter's private helpers rather than a shared layer, for the reason
        //  the Kotlin JSON emitter gives: the two have to agree, and a disagreement produces Swift
        //  that does not compile — the cheapest possible way to find out.

        private const string SimpleContentField = "Value";

        private static readonly HashSet<string> SwiftKeywords = new(StringComparer.Ordinal)
        {
            "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import",
            "init", "inout", "internal", "let", "open", "operator", "private", "precedencegroup",
            "protocol", "public", "rethrows", "static", "struct", "subscript", "typealias", "var",
            "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough",
            "for", "guard", "if", "in", "repeat", "return", "throw", "switch", "where", "while",
            "as", "any", "await", "false", "is", "nil", "self", "Self", "super", "throws", "true", "try",
        };

        private static string SStr(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

        private static string Ident(string name) => SwiftKeywords.Contains(name) ? "`" + name + "`" : name;

        private static string Camel(string pascal) =>
            pascal.Length == 0 ? pascal : char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);

        private static string Prop(string pascal) => Ident(Camel(pascal));

        private static string Type(TypeRef t) => t switch
        {
            TypeRef.Named n     => n.Name,
            TypeRef.Primitive p => p.Kind switch
            {
                PrimitiveKind.Bool   => "Bool",
                PrimitiveKind.Int8   => "Int8",
                PrimitiveKind.Int16  => "Int16",
                PrimitiveKind.Int32  => "Int32",
                PrimitiveKind.Int64  => "Int64",
                PrimitiveKind.UInt8  => "UInt8",
                PrimitiveKind.UInt16 => "UInt16",
                PrimitiveKind.UInt32 => "UInt32",
                PrimitiveKind.UInt64 => "UInt64",
                PrimitiveKind.String => "String",
                PrimitiveKind.Binary => "[UInt8]",
                _ => throw new NotSupportedException($"Swift JSON back end: primitive {p.Kind}."),
            },
            _ => throw new NotSupportedException("Swift JSON back end: untyped child."),
        };

    }
}
