/*
 * Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using NUnit.Framework;
using cloud.charging.open.protocols.ISO15118.AppProtocol;
using cloud.charging.open.protocols.ISO15118.EXI.Tests.Infrastructure;

namespace cloud.charging.open.protocols.ISO15118.EXI.Tests
{
    /// <summary>
    /// Vector-driven conformance tests for the AppProtocol codec.
    /// <para>
    /// Each vector is exercised three ways:
    /// <list type="number">
    ///   <item><b>Encode match</b> — encoder output must equal <c>expectedHex</c> byte-for-byte.</item>
    ///   <item><b>Decode match</b> — decoding <c>expectedHex</c> must yield the input message.</item>
    ///   <item><b>Roundtrip</b>    — encoded bytes decode back to the input.</item>
    /// </list>
    /// </para>
    /// <para>
    /// <b>What "passing" means.</b> The <c>expectedHex</c> in <c>AppProtocol.vectors.json</c>
    /// is generated by EVerest's libcbv2g at a pinned commit, so a passing run proves wire
    /// conformance against the de-facto ISO 15118 reference codec — not just internal
    /// self-consistency. Regenerate via <c>tools/regenerate-appprotocol-vectors.py</c>.
    /// </para>
    /// </summary>
    [TestFixture]
    public class AppProtocolVectorTests
    {
        [TestCaseSource(typeof(AppProtocolVectorSource), nameof(AppProtocolVectorSource.All))]
        public void Encode_Matches_Expected(string file, Vector v)
        {
            var expected = HexUtil.Parse(v.ExpectedHex);
            Assert.That(expected.Length, Is.EqualTo(v.ExpectedBytes),
                "vector's expectedBytes does not match the parsed length of expectedHex");

            // Generously sized buffer; tighter sizing comes once we have a max-size analysis.
            var buf = new byte[1024];
            int written;
            bool ok;

            switch (v.MessageType)
            {
                case "SupportedAppProtocolReq":
                    ok = SupportedAppProtocolCodec.TryEncodeRequest(
                        VectorInputBinder.BindRequest(v.Input), buf, out written);
                    break;
                case "SupportedAppProtocolRes":
                    ok = SupportedAppProtocolCodec.TryEncodeResponse(
                        VectorInputBinder.BindResponse(v.Input), buf, out written);
                    break;
                default:
                    throw new NotSupportedException(
                        $"Unknown messageType '{v.MessageType}' in {file} / {v.Name}.");
            }

            Assert.That(ok, Is.True, $"{file}/{v.Name}: encoder returned false");

            var actual = buf.AsSpan(0, written).ToArray();
            if (!actual.AsSpan().SequenceEqual(expected))
                Assert.Fail($"{file}/{v.Name}: encode mismatch\n{HexUtil.Diff(expected, actual)}");
        }

        [TestCaseSource(typeof(AppProtocolVectorSource), nameof(AppProtocolVectorSource.All))]
        public void Decode_Matches_Input(string file, Vector v)
        {
            var bytes   = HexUtil.Parse(v.ExpectedHex);
            var decoded = SupportedAppProtocolCodec.DecodeAny(bytes, out int consumed);

            Assert.That(consumed, Is.EqualTo(bytes.Length), "did not consume all bytes");

            switch (v.MessageType)
            {
                case "SupportedAppProtocolReq":
                {
                    var expReq = VectorInputBinder.BindRequest(v.Input);
                    Assert.That(decoded, Is.InstanceOf<SupportedAppProtocolReq>());
                    var gotReq = (SupportedAppProtocolReq)decoded;
                    Assert.That(gotReq.AppProtocols, Is.EqualTo(expReq.AppProtocols));
                    break;
                }
                case "SupportedAppProtocolRes":
                    Assert.That(decoded, Is.EqualTo(VectorInputBinder.BindResponse(v.Input)));
                    break;
                default:
                    throw new NotSupportedException(v.MessageType);
            }
        }

        [TestCaseSource(typeof(AppProtocolVectorSource), nameof(AppProtocolVectorSource.All))]
        public void Roundtrip(string file, Vector v)
        {
            var buf = new byte[1024];
            int written;

            switch (v.MessageType)
            {
                case "SupportedAppProtocolReq":
                {
                    var input = VectorInputBinder.BindRequest(v.Input);
                    Assert.That(
                        SupportedAppProtocolCodec.TryEncodeRequest(input, buf, out written),
                        Is.True);
                    var got = (SupportedAppProtocolReq)
                        SupportedAppProtocolCodec.DecodeAny(buf.AsSpan(0, written), out _);
                    Assert.That(got.AppProtocols, Is.EqualTo(input.AppProtocols));
                    break;
                }
                case "SupportedAppProtocolRes":
                {
                    var input = VectorInputBinder.BindResponse(v.Input);
                    Assert.That(
                        SupportedAppProtocolCodec.TryEncodeResponse(input, buf, out written),
                        Is.True);
                    Assert.That(
                        SupportedAppProtocolCodec.DecodeAny(buf.AsSpan(0, written), out _),
                        Is.EqualTo(input));
                    break;
                }
                default:
                    throw new NotSupportedException(v.MessageType);
            }
        }
    }
}
