/*
 * Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Text.Json;
using NUnit.Framework;
using cloud.charging.open.protocols.ISO15118.EXI.Tests.Infrastructure;
using cloud.charging.open.protocols.ISO15118_2.Generated;

namespace cloud.charging.open.protocols.ISO15118.EXI.Tests
{
    /// <summary>
    /// Differential wire conformance for ISO 15118-2: the generated codec must produce exactly the
    /// bytes cbV2G produces for each target message (SessionSetupReq/Res, ServiceDiscoveryReq/Res).
    /// The reference hex is checked in (<c>Vectors/Iso15118_2.vectors.json</c>, emitted by
    /// <c>tools/cbv2g-ref/main_iso2.c</c>); the message for each vector name comes from
    /// <see cref="Iso15118_2Fixtures"/>.
    /// </summary>
    [TestFixture]
    public class Iso15118_2VectorTests
    {
        public sealed record Vec(string Name, string MessageType, string ExpectedHex);

        private static IEnumerable<TestCaseData> Vectors()
        {
            var path = Path.Combine(TestContext.CurrentContext.TestDirectory, "Vectors", "Iso15118_2.vectors.json");
            using var doc = JsonDocument.Parse(File.ReadAllText(path));
            foreach (var v in doc.RootElement.GetProperty("vectors").EnumerateArray())
            {
                var name = v.GetProperty("name").GetString()!;
                yield return new TestCaseData(new Vec(
                    name,
                    v.GetProperty("messageType").GetString()!,
                    v.GetProperty("expectedHex").GetString()!)).SetName(name);
            }
        }

        [TestCaseSource(nameof(Vectors))]
        public void GeneratedCodec_Matches_CbV2G(Vec vector)
        {
            Assert.That(Iso15118_2Fixtures.ByName.ContainsKey(vector.Name), Is.True,
                $"no fixture for vector '{vector.Name}'");

            var message = Iso15118_2Fixtures.ByName[vector.Name];
            var buf = new byte[512];
            Assert.That(message.TryEncode(buf, out int n), Is.True, "encode failed");

            var actual = buf.AsSpan(0, n).ToArray();
            var expected = ParseHex(vector.ExpectedHex);

            if (!actual.AsSpan().SequenceEqual(expected))
                Assert.Fail($"{vector.Name}: generated bytes diverge from cbV2G.\n" +
                            $"  expected ({expected.Length}): {ToHex(expected)}\n" +
                            $"  actual   ({actual.Length}): {ToHex(actual)}");
        }

        private static byte[] ParseHex(string hex)
        {
            var parts = hex.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            var bytes = new byte[parts.Length];
            for (int i = 0; i < parts.Length; i++)
                bytes[i] = Convert.ToByte(parts[i], 16);
            return bytes;
        }

        private static string ToHex(byte[] b) => string.Join(' ', b.Select(x => x.ToString("x2")));
    }
}
