/*
 * Copyright (c) 2021-2026 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Text.Json;
using System.Text.Json.Nodes;
using NUnit.Framework;
using cloud.charging.open.protocols.ISO15118.EXI.Tests.Infrastructure;

namespace cloud.charging.open.protocols.ISO15118.EXI.Tests
{

    /// <summary>
    /// The JSON-LD documents themselves, checked in — every vector in the corpus, as text.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Why this exists, and it is not redundancy.</b> <see cref="JsonLdRoundtripTests"/> proves the
    /// mapping loses nothing, and it is blind to what the mapping is *called*: rename every property
    /// in the emitter and the round trip stays green, because both directions change together. That
    /// was measured, not assumed — replacing the naming rule with a naïve
    /// lower-the-first-character one left all 163 round-trip tests passing while turning
    /// <c>evseStatus</c> into <c>eVSEStatus</c> in every message of every set.
    /// </para>
    /// <para>
    /// §4.4 names cross-language agreement as the compensation for exactly this, "once a second
    /// backend exists". This file is that agreement's corpus, written while only one exists: the
    /// Kotlin and Swift JSON-LD emitters will be held to these bytes rather than to a second reading
    /// of the naming rules. Until then it still earns its place — a property name is part of a wire
    /// format the moment anything outside this repository reads it, and a rename that no test notices
    /// is a breaking change that no test notices.
    /// </para>
    /// <para>
    /// It pins more than names: property <b>order</b>, <c>@context</c> and <c>@type</c> placement,
    /// hex for binary, strings for 64-bit integers, and which optional properties are omitted rather
    /// than written as null.
    /// </para>
    /// </remarks>
    [TestFixture]
    public class JsonLdDocumentCorpusTests
    {

        private static readonly (JsonLdBridge Bridge, string Vectors)[] Sets = [
            (JsonLdBridge.AppProtocol, "AppProtocol.vectors.json"),
            (JsonLdBridge.Iso2,        "Iso15118_2.vectors.json"),
            (JsonLdBridge.Common,      "Iso15118_20.CommonMessages.vectors.json"),
            (JsonLdBridge.Dc,          "Iso15118_20.DC.vectors.json"),
            (JsonLdBridge.Ac,          "Iso15118_20.AC.vectors.json"),
            (JsonLdBridge.Wpt,         "Iso15118_20.WPT.vectors.json"),
            (JsonLdBridge.Acdp,        "Iso15118_20.ACDP.vectors.json"),
            (JsonLdBridge.AcDerIec,    "Iso15118_20.AC_DER_IEC.vectors.json"),
            (JsonLdBridge.AcDerSae,    "Iso15118_20.AC_DER_SAE.vectors.json"),
        ];

        private const string CorpusFile = "JsonLd.documents.json";

        private static readonly JsonSerializerOptions Pretty = new() { WriteIndented = true };


        /// <summary>Every vector, decoded and serialized — the shape the corpus stores.</summary>
        private static JsonObject Produce()
        {

            var sets = new JsonObject();

            foreach (var (bridge, vectorFile) in Sets)
            {

                var documents = new JsonObject { ["@context"] = bridge.Context };

                foreach (var (name, hex) in ReadVectors(vectorFile))
                    documents[name] = bridge.ToJSON(bridge.Decode(HexUtil.Parse(hex), out _));

                sets[bridge.Name] = documents;

            }

            return new JsonObject {
                ["note"] = "Generated by JsonLdDocumentCorpusTests.RegenerateTheCorpus. Every vector "
                         + "in the wire corpus, as the JSON-LD form of the same message. This is what "
                         + "the Kotlin and Swift JSON-LD emitters must reproduce character for "
                         + "character — the EXI -> JSON -> EXI round trip cannot see property names, "
                         + "because both directions rename together.",
                ["sets"] = sets,
            };

        }


        [Test, Explicit("Rewrites the checked-in JSON-LD documents. Run deliberately, and read the diff.")]
        public void RegenerateTheCorpus()
        {

            File.WriteAllText(SourcePath, Produce().ToJsonString(Pretty));

            TestContext.Out.WriteLine($"{Sets.Length} message sets -> {SourcePath}");

        }


        /// <summary>
        /// The corpus must cover every vector, not merely agree about the ones it happens to contain.
        /// <para>
        /// <see cref="EveryDocumentIsUnchanged"/> walks the checked-in documents and compares each
        /// against what this build produces, which catches a document that <i>changed</i> and is blind
        /// to one that was never added. That is not hypothetical: six vectors were added on 2026-08-08
        /// and the whole fixture stayed green while none of them had a pinned JSON-LD form. The two
        /// directions are different questions and this is the other one.
        /// </para>
        /// </summary>
        [Test]
        public void EveryVectorIsInTheCorpus()
        {

            var expected = JsonNode.Parse(File.ReadAllText(CorpusPath))!.AsObject()["sets"]!.AsObject();
            var actual   = Produce()["sets"]!.AsObject();

            var missing = new List<string>();

            foreach (var (setName, actualSet) in actual)
                foreach (var (documentName, _) in actualSet!.AsObject())
                    if (documentName != "@context" &&
                        expected[setName]?.AsObject().ContainsKey(documentName) != true)
                        missing.Add($"{setName}/{documentName}");

            Assert.That(missing, Is.Empty,
                        "vectors with no JSON-LD document — run RegenerateTheCorpus and read the diff:\n  " +
                        string.Join("\n  ", missing));

        }


        /// <summary>The checked-in documents, against what this build produces.</summary>
        [Test]
        public void EveryDocumentIsUnchanged()
        {

            Assert.That(File.Exists(CorpusPath), Is.True,
                        $"the JSON-LD document corpus is missing at {CorpusPath}");

            var expected = JsonNode.Parse(File.ReadAllText(CorpusPath))!.AsObject()["sets"]!.AsObject();
            var actual   = Produce()["sets"]!.AsObject();

            foreach (var (setName, expectedSet) in expected)
            {

                Assert.That(actual.ContainsKey(setName), Is.True, $"{setName} is no longer produced");

                foreach (var (documentName, expectedDocument) in expectedSet!.AsObject())
                {

                    var actualDocument = actual[setName]!.AsObject()[documentName];

                    Assert.That(actualDocument, Is.Not.Null,
                                $"{setName}/{documentName} is no longer produced");

                    // Compared as text so that property ORDER counts. Two objects with the same
                    // entries in a different order are equal as data and different as a document,
                    // and a second back end has to match the document.
                    Assert.That(actualDocument!.ToJsonString(Pretty),
                                Is.EqualTo(expectedDocument!.ToJsonString(Pretty)),
                                $"{setName}/{documentName} changed");

                }

            }

        }


        /// <summary>
        /// The corpus still covers what it was built to cover.
        /// </summary>
        /// <remarks>
        /// A corpus that quietly lost a message set would keep passing forever, and this one is
        /// generated — the failure mode of every generated fixture.
        /// </remarks>
        [Test]
        public void TheCorpusStillCoversEveryMessageSet()
        {

            var sets = JsonNode.Parse(File.ReadAllText(CorpusPath))!.AsObject()["sets"]!.AsObject();

            Assert.That(sets.Count, Is.EqualTo(Sets.Length));

            foreach (var (bridge, _) in Sets)
            {
                Assert.That(sets.ContainsKey(bridge.Name), Is.True, $"{bridge.Name} is missing");
                Assert.That(sets[bridge.Name]!.AsObject().Count, Is.GreaterThan(1),
                            $"{bridge.Name} has no documents");
            }

        }


        // ── plumbing ──────────────────────────────────────────────────────────

        private static IEnumerable<(string Name, string Hex)> ReadVectors(string fileName)
        {
            var path = Path.Combine(TestContext.CurrentContext.TestDirectory, "Vectors", fileName);
            using var doc = JsonDocument.Parse(File.ReadAllText(path));

            foreach (var v in doc.RootElement.GetProperty("vectors").EnumerateArray())
                yield return (v.GetProperty("name").GetString()!, v.GetProperty("expectedHex").GetString()!);
        }

        private static string CorpusPath =>
            Path.Combine(TestContext.CurrentContext.TestDirectory, "Vectors", CorpusFile);

        /// <summary>The file in the source tree, not the copy beside the test binary.</summary>
        private static string SourcePath
        {
            get
            {
                // Anchored on the test project's own directory rather than on a repository marker
                // such as CLAUDE.md: the codec now lives inside the WWCP_ISO15118 submodule, so the
                // nearest CLAUDE.md above this is the *parent* repository's, several levels too far
                // out. This is the same idiom EmitterHarness.RealSchemaSet uses.
                var directory = new DirectoryInfo(TestContext.CurrentContext.TestDirectory);
                while (directory is not null &&
                       !Directory.Exists(Path.Combine(directory.FullName, "WWCP_ISO15118_EXI_Tests")))
                    directory = directory.Parent;

                return Path.Combine(directory!.FullName, "WWCP_ISO15118_EXI_Tests", "Vectors", CorpusFile);
            }
        }

    }

}
