/*
 * Copyright (c) 2021-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System.Collections.Concurrent;
using cloud.charging.open.protocols.ISO15118.SLAC.Messages;
using cloud.charging.open.protocols.ISO15118.SLAC.Transport;
using org.GraphDefined.Vanaheimr.Hermod.Ethernet;

namespace cloud.charging.open.protocols.ISO15118.SLAC.StateMachine;

/// <summary>
/// Long-running EVSE-side SLAC listener. Subscribes to the transport's
/// <see cref="ISlacTransport.FrameReceived"/> event, demultiplexes incoming
/// frames by RunID, and spawns one <see cref="EvseSlacSession"/> per PEV.
/// </summary>
/// <remarks>
/// A real charging station with multiple outlets will see several PEVs
/// initiate SLAC matching at the same time. Each attempt carries a unique
/// 8-byte RunID generated by the PEV in CM_SLAC_PARM.REQ. The listener uses
/// that RunID as the demux key — frames whose RunID does not match any
/// active session are silently dropped.
/// </remarks>
public sealed class EvseSlacListener : IAsyncDisposable
{

    private readonly ISlacTransport                              _transport;
    private readonly Func<EvseSlacOptions>                       _optionsFactory;
    private readonly ConcurrentDictionary<RunId, SessionEntry>   _sessions = new();
    private readonly CancellationTokenSource                     _cts      = new();

    /// <summary>Fired when a new PEV's CM_SLAC_PARM.REQ has just spawned a session.</summary>
    public event EventHandler<EvseSlacSession>?                  SessionStarted;

    /// <summary>Fired when a session has successfully completed CM_SLAC_MATCH.CNF.</summary>
    public event EventHandler<SlacSessionCompletedEventArgs>?    SessionCompleted;

    /// <summary>Fired when a session has failed (timeout, cancellation, protocol error).</summary>
    public event EventHandler<SlacSessionFailedEventArgs>?       SessionFailed;

    /// <summary>Fired for listener-level events that are not bound to a session.</summary>
    public event EventHandler<string>?                           Log;

    /// <summary>Snapshot of currently active sessions, keyed by RunID.</summary>
    public IReadOnlyDictionary<RunId, EvseSlacSession> ActiveSessions
        => _sessions.ToDictionary(kvp => kvp.Key, kvp => kvp.Value.Session);

    /// <param name="transport">The SLAC transport to listen on.</param>
    /// <param name="optionsFactory">
    /// Factory invoked once per new PEV. Use this to generate a fresh NID/NMK
    /// per matching session.
    /// </param>
    public EvseSlacListener(ISlacTransport transport, Func<EvseSlacOptions> optionsFactory)
    {
        _transport      = transport;
        _optionsFactory = optionsFactory;
    }

    /// <summary>Start dispatching frames. Call once after construction.</summary>
    public Task StartAsync(CancellationToken cancellationToken = default)
    {
        _transport.FrameReceived += OnFrameReceived;
        return Task.CompletedTask;
    }

    private void OnFrameReceived(object? sender, DecodedFrame frame)
    {
        switch (frame.Message)
        {
            case SLACParamReq parmReq:
                HandleParmReq(parmReq, frame.Source);
                break;

            // Subsequent frames belong to an existing session, looked up by RunID.
            case StartAttenCharInd m: Dispatch(m.RunId, frame); break;
            case MnbcSoundInd      m: Dispatch(m.RunId, frame); break;
            case AttenCharRsp      m: Dispatch(m.RunId, frame); break;
            case SlacMatchReq      m: Dispatch(m.RunId, frame); break;

            // CM_VALIDATE messages do not carry a RunID — dispatch by the
            // sender's MAC, which is unique to one running session.
            case ValidateCnf:         DispatchByPevMac(frame); break;

            // The EVSE never receives its own indications/confirmations, so
            // CM_SLAC_PARM.CNF, CM_ATTEN_CHAR.IND, CM_SLAC_MATCH.CNF would be
            // an oddity here — drop them.
            default:
                break;
        }
    }

    private void Dispatch(RunId runId, DecodedFrame frame)
    {
        if (_sessions.TryGetValue(runId, out var entry))
            entry.Session.EnqueueFrame(frame);
        // else: orphan frame for an unknown / already-finished session — drop.
    }

    private void DispatchByPevMac(DecodedFrame frame)
    {
        // Linear scan: the active-session count is always small (= number of
        // simultaneously plugged-in PEVs), and ValidateCnf frames are rare.
        foreach (var entry in _sessions.Values)
        {
            if (entry.Session.PevMac == frame.Source)
            {
                entry.Session.EnqueueFrame(frame);
                return;
            }
        }
        // else: orphan — drop.
    }

    private void HandleParmReq(SLACParamReq parmReq, MACAddress pevMac)
    {
        // Retransmits of the same CM_SLAC_PARM.REQ (same RunID) are ignored —
        // the existing session has already replied with CM_SLAC_PARM.CNF.
        if (_sessions.ContainsKey(parmReq.RunId))
            return;

        EvseSlacOptions options;
        try
        {
            options = _optionsFactory();
        }
        catch (Exception ex)
        {
            LogInfo($"Options factory threw for RunID {parmReq.RunId}: {ex.Message}");
            return;
        }

        var session   = new EvseSlacSession(_transport, options, parmReq.RunId, pevMac);
        var sessionCt = CancellationTokenSource.CreateLinkedTokenSource(_cts.Token);

        // Gate the worker until handlers attached in SessionStarted have run.
        // Without this, fast state transitions could fire before the user has
        // attached StateChanged / Log handlers.
        var startGate = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);

        var worker = Task.Run(async () =>
        {
            await startGate.Task.ConfigureAwait(false);

            try
            {
                var result = await session.RunAsync(sessionCt.Token).ConfigureAwait(false);
                SessionCompleted?.Invoke(this, new SlacSessionCompletedEventArgs(session, result));
            }
            catch (OperationCanceledException) when (_cts.IsCancellationRequested)
            {
                // Listener is shutting down — silent, not a session failure.
            }
            catch (Exception ex)
            {
                SessionFailed?.Invoke(this, new SlacSessionFailedEventArgs(session, ex));
            }
            finally
            {
                _sessions.TryRemove(parmReq.RunId, out _);
                await session.DisposeAsync().ConfigureAwait(false);
                sessionCt.Dispose();
            }
        });

        var entry = new SessionEntry(session, worker, sessionCt);
        if (!_sessions.TryAdd(parmReq.RunId, entry))
        {
            // Race: another thread already added a session for this RunID.
            sessionCt.Cancel();
            startGate.TrySetResult();
            return;
        }

        // Allow user code to subscribe to events on the new session BEFORE the
        // worker starts running it.
        SessionStarted?.Invoke(this, session);

        startGate.SetResult();
    }

    private void LogInfo(string msg) => Log?.Invoke(this, msg);

    public async ValueTask DisposeAsync()
    {
        _transport.FrameReceived -= OnFrameReceived;
        _cts.Cancel();

        var workers = _sessions.Values.Select(e => e.Worker).ToArray();
        if (workers.Length > 0)
        {
            try   { await Task.WhenAll(workers).ConfigureAwait(false); }
            catch { /* failures already surfaced via SessionFailed */ }
        }

        _cts.Dispose();
    }

    private sealed record SessionEntry(
        EvseSlacSession         Session,
        Task                    Worker,
        CancellationTokenSource Cts);
}

public sealed record SlacSessionCompletedEventArgs(EvseSlacSession Session, SlacMatchCnf Result);

public sealed record SlacSessionFailedEventArgs(EvseSlacSession Session, Exception Error);
