/*
 * Copyright (c) 2021-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace cloud.charging.open.protocols.ISO15118.SLAC
{

    /// <summary>
    /// 8-byte RunID identifying a single SLAC matching attempt.
    /// Generated by the EV in CM_SLAC_PARM.REQ and echoed by the EVSE in all
    /// subsequent frames belonging to this matching session.
    /// </summary>
    public readonly struct RunId : IEquatable<RunId>
    {

        private readonly ulong _value;

        public RunId(ReadOnlySpan<Byte> bytes)
        {
            if (bytes.Length != SLACConstants.RunIdLength)
                throw new ArgumentException("RunID must be exactly 8 bytes long.", nameof(bytes));

            _value = BitConverter.ToUInt64(bytes);
        }

        private RunId(ulong value) => _value = value;

        public static RunId NewRandom()
        {
            Span<byte> bytes = stackalloc byte[SLACConstants.RunIdLength];
            System.Security.Cryptography.RandomNumberGenerator.Fill(bytes);
            return new RunId(BitConverter.ToUInt64(bytes));
        }

        public Byte[] ToArray()
        {
            var result = new Byte[SLACConstants.RunIdLength];
            BitConverter.TryWriteBytes(result, _value);
            return result;
        }

        public void CopyTo(Span<byte> destination)
        {
            if (destination.Length < SLACConstants.RunIdLength)
                throw new ArgumentException("Destination span too small.", nameof(destination));

            BitConverter.TryWriteBytes(destination, _value);
        }

        public bool Equals(RunId other) => _value == other._value;
        public override bool Equals(object? obj) => obj is RunId r && Equals(r);
        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(RunId left, RunId right) => left.Equals(right);
        public static bool operator !=(RunId left, RunId right) => !left.Equals(right);

        public override string ToString() => $"0x{_value:X16}";

    }

}
