<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:iso:std:iso:15118:-20:AC-DER-SAE" xmlns:v2gci_ct="urn:iso:std:iso:15118:-20:CommonTypes" xmlns:v2gci_ac="urn:iso:std:iso:15118:-20:AC" targetNamespace="urn:iso:std:iso:15118:-20:AC-DER-SAE" elementFormDefault="qualified" attributeFormDefault="qualified" version="15118:-20:Amd1">
	<xs:import namespace="urn:iso:std:iso:15118:-20:CommonTypes" schemaLocation="V2G_CI_CommonTypes.xsd"/>
	<xs:import namespace="urn:iso:std:iso:15118:-20:AC" schemaLocation="V2G_CI_AC.xsd"/>
	<!--             -->
	<!-- ––––––––––– -->
	<!-- AC Messages -->
	<!-- ––––––––––– -->
	<!--                               -->
	<!-- AC Charge Parameter Discovery -->
	<!--                               -->
    <!--	
	<xs:element name="AC_ChargeParameterDiscoveryReq" type="v2gci_ac:AC_ChargeParameterDiscoveryReqType"/>
	<xs:element name="AC_ChargeParameterDiscoveryRes" type="v2gci_ac:AC_ChargeParameterDiscoveryResType"/>
    -->
	<!--                -->
	<!-- AC Charge Loop -->
	<!--                -->
	<!--
	<xs:element name="AC_ChargeLoopReq" type="v2gci_ac:AC_ChargeLoopReqType"/>
	<xs:element name="AC_ChargeLoopRes" type="v2gci_ac:AC_ChargeLoopResType"/>
	-->
	<!--                        -->
	<!-- –––––––––––––––––––––– -->
	<!-- Message Specific Types -->
	<!-- –––––––––––––––––––––– -->
	<!--                               -->
	<!-- AC Charge Parameter Discovery -->
	<!--                               -->
	<!-- Energy Transfer Mode - AC -->
	<!-- Energy Transfer Mode - AC BPT -->
	<!-- Energy Transfer Mode - AC DER -->
	<!-- Energy Transfer Mode - AC DER - Req -->
	<xs:element name="DER_AC_CPDReqEnergyTransferMode" type="DER_AC_CPDReqEnergyTransferModeType" substitutionGroup="v2gci_ac:AC_CPDReqEnergyTransferMode"/>
	<xs:complexType name="DER_AC_CPDReqEnergyTransferModeType">
		<xs:complexContent>
			<xs:extension base="v2gci_ac:AC_CPDReqEnergyTransferModeType">
				<xs:sequence>
					<xs:element name="EVProcessing" type="v2gci_ct:processingType"/>
					<xs:element name="EVMaximumDischargePower" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVMaximumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMaximumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSessionTotalDischargeEnergyAvailable" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVApparentPowerLimits" type="EVApparentPowerLimitsType"/>
					<xs:element name="EVReactivePowerLimits" type="EVReactivePowerLimitsType"/>
					<xs:element name="EVExcitationLimits" type="EVExcitationLimitsType"/>
					<xs:element name="EVInverterDetails" type="EVInverterDetailsType"/>
					<xs:element name="IEEE1547NormalCategory" type="ieee1547NormalCategoryType"/>
					<xs:element name="IEEE1547AbnormalCategory" type="ieee1547AbnormalCategoryType"/>
					<xs:element name="EVNominalVoltage" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVMaximumVoltage" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVMinimumVoltage" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVNominalVoltageOffset" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="J3072Certified" type="xs:boolean"/>
					<xs:element name="J3072CertificationDate" type="xs:unsignedLong"/>
					<xs:element name="EVUseableWattHours" type="xs:unsignedInt"/>
					<xs:element name="EVUpdateTime" type="xs:unsignedLong"/>
					<xs:element name="SupportedModes" type="xs:unsignedInt"/>
					<xs:element name="EnabledModes" type="xs:unsignedInt"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Energy Transfer Mode - AC DER - Res -->
	<xs:element name="DER_AC_CPDResEnergyTransferMode" type="DER_AC_CPDResEnergyTransferModeType" substitutionGroup="v2gci_ac:AC_CPDResEnergyTransferMode"/>
	<xs:complexType name="DER_AC_CPDResEnergyTransferModeType">
		<xs:complexContent>
			<xs:extension base="v2gci_ac:AC_CPDResEnergyTransferModeType">
				<xs:sequence>
					<xs:element name="EVSEProcessing" type="v2gci_ct:processingType"/>
					<xs:element name="EVSEStatus" type="v2gci_ct:EVSEStatusType" minOccurs="0"/>
					<xs:element name="DERControlCPDRes" type="DERControlCPDResType"/>
					<xs:element name="EVSENominalChargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSENominalChargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSENominalChargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSENominalDischargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSENominalDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSENominalDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVSEMaximumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEReactivePowerLimits" type="EVSEReactivePowerLimitsType"/>
					<xs:element name="GridLimits" type="GridLimitsType"/>
					<xs:element name="RequiredDEROperatingMode" type="requiredDEROperatingModeType"/>
					<xs:element name="GridConnectionMode" type="gridConnectionModeType"/>
					<xs:element name="EVSEUpdateTime" type="xs:unsignedLong"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!--                -->
	<!-- AC Charge Loop -->
	<!--                -->
	<!-- Control Modes - Scheduled -->
	<!-- Control Modes - Scheduled - BPT -->
	<!-- Control Modes - Scheduled - DER -->
	<!-- Control Modes - Scheduled - DER - Req -->
	<xs:element name="DER_Scheduled_AC_CLReqControlMode" type="DER_Scheduled_AC_CLReqControlModeType" substitutionGroup="v2gci_ac:Scheduled_AC_CLReqControlMode"/>
	<xs:complexType name="DER_Scheduled_AC_CLReqControlModeType">
		<xs:complexContent>
			<xs:extension base="v2gci_ac:Scheduled_AC_CLReqControlModeType">
				<xs:sequence>
					<xs:element name="EVPresentVoltage" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVPresentFrequency" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVMaximumDischargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMaximumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMaximumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="DEROperationalState" type="derOperationalStateType"/>
					<xs:element name="DERConnectionStatus" type="derConnectionStatusType"/>
					<xs:element name="EVApparentPower" type="EVApparentPowerType" minOccurs="0"/>
					<xs:element name="EVReactivePower" type="EVReactivePowerType" minOccurs="0"/>
					<xs:element name="EVExcitation" type="EVExcitationType" minOccurs="0"/>
					<xs:element name="EVUpdateTime" type="xs:unsignedLong"/>
					<xs:element name="EVMinimumChargingDuration" type="xs:unsignedInt" minOccurs="0"/>
					<xs:element name="EVDurationMaximumChargeRate" type="xs:unsignedInt" minOccurs="0"/>
					<xs:element name="EVDurationMaximumDischargeRate" type="xs:unsignedInt" minOccurs="0"/>
					<xs:element name="DERAlarmStatus" type="xs:unsignedInt"/>
					<xs:element name="EnabledModes" type="xs:unsignedInt"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Control Modes - Scheduled - DER - Res -->
	<xs:element name="DER_Scheduled_AC_CLResControlMode" type="DER_Scheduled_AC_CLResControlModeType" substitutionGroup="v2gci_ac:Scheduled_AC_CLResControlMode"/>
	<xs:complexType name="DER_Scheduled_AC_CLResControlModeType">
		<xs:complexContent>
			<xs:extension base="v2gci_ac:Scheduled_AC_CLResControlModeType">
				<xs:sequence>
					<xs:element name="DERControlCLRes" type="DERControlCLResType"/>
					<xs:element name="EVSEMaximumChargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumChargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumChargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="RequiredDEROperatingMode" type="requiredDEROperatingModeType" minOccurs="0"/>
					<xs:element name="GridConnectionMode" type="gridConnectionModeType" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Control Modes - Dynamic -->
	<!-- Control Modes - Dynamic - BPT -->
	<!-- Control Modes - Dynamic - BPT - DER -->
	<xs:element name="DER_Dynamic_AC_CLReqControlMode" type="DER_Dynamic_AC_CLReqControlModeType" substitutionGroup="v2gci_ac:Dynamic_AC_CLReqControlMode"/>
	<xs:complexType name="DER_Dynamic_AC_CLReqControlModeType">
		<xs:complexContent>
			<xs:extension base="v2gci_ac:Dynamic_AC_CLReqControlModeType">
				<xs:sequence>
					<xs:element name="EVMaximumDischargePower" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVMaximumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMaximumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVMinimumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVPresentVoltage" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVPresentFrequency" type="v2gci_ct:RationalNumberType"/>
					<xs:element name="EVSessionTotalDischargeEnergyAvailable" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVApparentPower" type="EVApparentPowerType" minOccurs="0"/>
					<xs:element name="EVReactivePower" type="EVReactivePowerType" minOccurs="0"/>
					<xs:element name="EVExcitation" type="EVExcitationType" minOccurs="0"/>
					<xs:element name="EVMaximumV2XEnergyRequest" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVMinimumV2XEnergyRequest" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="DEROperationalState" type="derOperationalStateType"/>
					<xs:element name="DERConnectionStatus" type="derConnectionStatusType"/>
					<xs:element name="EVUpdateTime" type="xs:unsignedLong"/>
					<xs:element name="EVMinimumChargingDuration" type="xs:unsignedInt"/>
					<xs:element name="EVDurationMaximumChargeRate" type="xs:unsignedInt"/>
					<xs:element name="EVDurationMaximumDischargeRate" type="xs:unsignedInt"/>
					<xs:element name="DERAlarmStatus" type="xs:unsignedInt"/>
					<xs:element name="EnabledModes" type="xs:unsignedInt"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="DER_Dynamic_AC_CLResControlMode" type="DER_Dynamic_AC_CLResControlModeType" substitutionGroup="v2gci_ac:Dynamic_AC_CLResControlMode"/>
	<xs:complexType name="DER_Dynamic_AC_CLResControlModeType">
		<xs:complexContent>
			<xs:extension base="v2gci_ac:Dynamic_AC_CLResControlModeType">
				<xs:sequence>
					<xs:element name="DERControlCLRes" type="DERControlCLResType"/>
					<xs:element name="EVSEMaximumChargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumChargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumChargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="EVSEMaximumDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
					<xs:element name="RequiredDEROperatingMode" type="requiredDEROperatingModeType" minOccurs="0"/>
					<xs:element name="GridConnectionMode" type="gridConnectionModeType" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="DERControlCPDResType">
		<xs:sequence>
			<xs:element name="VoltageTrip" type="VoltageTripType"/>
			<xs:element name="FrequencyTrip" type="FrequencyTripType"/>
			<xs:element name="EnterServiceCPDRes" type="EnterServiceCPDResType"/>
			<xs:element name="ReactivePowerSupportCPDRes" type="ReactivePowerSupportCPDResType"/>
			<xs:element name="ActivePowerSupportCPDRes" type="ActivePowerSupportCPDResType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DERControlCLResType">
		<xs:sequence>
			<xs:element name="VoltageTrip" type="VoltageTripType" minOccurs="0"/>
			<xs:element name="FrequencyTrip" type="FrequencyTripType" minOccurs="0"/>
			<xs:element name="EnterServiceCLRes" type="EnterServiceCLResType"/>
			<xs:element name="ReactivePowerSupportCLRes" type="ReactivePowerSupportCLResType" minOccurs="0"/>
			<xs:element name="ActivePowerSupportCLRes" type="ActivePowerSupportCLResType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="VoltageTripType">
		<xs:sequence>
			<xs:element name="OverVoltageMustTripCurve" type="DERCurveType"/>
			<xs:element name="UnderVoltageMustTripCurve" type="DERCurveType"/>
			<xs:element name="OverVoltageMomentaryCessationTripCurve" type="DERCurveType" minOccurs="0"/>
			<xs:element name="UnderVoltageMomentaryCessationTripCurve" type="DERCurveType" minOccurs="0"/>
			<xs:element name="OverVoltageMayTripCurve" type="DERCurveType" minOccurs="0"/>
			<xs:element name="UnderVoltageMayTripCurve" type="DERCurveType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FrequencyTripType">
		<xs:sequence>
			<xs:element name="OverFrequencyMustTripCurve" type="DERCurveType"/>
			<xs:element name="UnderFrequencyMustTripCurve" type="DERCurveType"/>
			<xs:element name="OverFrequencyMayTripCurve" type="DERCurveType" minOccurs="0"/>
			<xs:element name="UnderFrequencyMayTripCurve" type="DERCurveType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EnterServiceCPDResType">
		<xs:sequence>
			<xs:element name="PermitService" type="xs:boolean"/>
			<xs:element name="EnterServiceVoltageHigh" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EnterServiceVoltageLow" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EnterServiceFrequencyHigh" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EnterServiceFrequencyLow" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EnterServiceDelay" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceRandomizedDelay" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceRampTime" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EnterServiceCLResType">
		<xs:sequence>
			<xs:element name="PermitService" type="xs:boolean"/>
			<xs:element name="EnterServiceVoltageHigh" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceVoltageLow" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceFrequencyHigh" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceFrequencyLow" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceDelay" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceRandomizedDelay" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EnterServiceRampTime" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReactivePowerSupportCPDResType">
		<xs:sequence>
			<xs:element name="ConstantPowerFactor" type="ConstantPowerFactorType"/>
			<xs:element name="VoltVar" type="VoltVarType"/>
			<xs:element name="WattVar" type="WattVarType"/>
			<xs:element name="ConstantVar" type="ConstantVarType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ReactivePowerSupportCLResType">
		<xs:sequence>
			<xs:element name="ConstantPowerFactor" type="ConstantPowerFactorType" minOccurs="0"/>
			<xs:element name="VoltVar" type="VoltVarType" minOccurs="0"/>
			<xs:element name="WattVar" type="WattVarType" minOccurs="0"/>
			<xs:element name="ConstantVar" type="ConstantVarType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ActivePowerSupportCPDResType">
		<xs:sequence>
			<xs:element name="FrequencyDroop" type="FrequencyDroopType"/>
			<xs:element name="VoltWatt" type="VoltWattType"/>
			<xs:element name="ConstantWatt" type="ConstantWattType"/>
			<xs:element name="LimitMaxDischargePower" type="LimitMaxDischargePowerType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ActivePowerSupportCLResType">
		<xs:sequence>
			<xs:element name="FrequencyDroop" type="FrequencyDroopType" minOccurs="0"/>
			<xs:element name="VoltWatt" type="VoltWattType" minOccurs="0"/>
			<xs:element name="ConstantWatt" type="ConstantWattType" minOccurs="0"/>
			<xs:element name="LimitMaxDischargePower" type="LimitMaxDischargePowerType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ConstantPowerFactorType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="PowerFactorValue" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="PowerFactorValue_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="PowerFactorValue_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="PowerFactorExcitation" type="powerFactorExcitationType"/>
			<xs:element name="PowerFactorExcitation_L2" type="powerFactorExcitationType" minOccurs="0"/>
			<xs:element name="PowerFactorExcitation_L3" type="powerFactorExcitationType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ConstantVarType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="VarSetpoint" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="VarSetpoint_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="VarSetpoint_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="Unit" type="derUnitType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ConstantWattType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="WattSetpoint" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="WattSetpoint_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="WattSetpoint_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="Unit" type="derUnitType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DERCurveType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="xUnit" type="derUnitType"/>
			<xs:element name="yUnit" type="derUnitType"/>
			<xs:element name="CurveDataPoints" type="CurveDataPointsListType"/>
			<xs:element name="CurveDataPoints_L2" type="CurveDataPointsListType" minOccurs="0"/>
			<xs:element name="CurveDataPoints_L3" type="CurveDataPointsListType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="VoltVarType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="xUnit" type="derUnitType"/>
			<xs:element name="yUnit" type="derUnitType"/>
			<xs:element name="CurveDataPoints" type="CurveDataPointsListType"/>
			<xs:element name="CurveDataPoints_L2" type="CurveDataPointsListType" minOccurs="0"/>
			<xs:element name="CurveDataPoints_L3" type="CurveDataPointsListType" minOccurs="0"/>
			<xs:element name="OpenLoopResponseTime" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="TimeConstantPT1" type="xs:unsignedInt" minOccurs="0"/>
			<xs:element name="ReferenceVoltage" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="AutonomousReferenceVoltageAdjustmentEnable" type="xs:boolean"/>
			<xs:element name="ReferenceVoltageAdjustmentTimeConstant" type="xs:unsignedInt"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WattVarType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="xUnit" type="derUnitType"/>
			<xs:element name="yUnit" type="derUnitType"/>
			<xs:element name="CurveDataPoints" type="CurveDataPointsListType"/>
			<xs:element name="CurveDataPoints_L2" type="CurveDataPointsListType" minOccurs="0"/>
			<xs:element name="CurveDataPoints_L3" type="CurveDataPointsListType" minOccurs="0"/>
			<xs:element name="OpenLoopResponseTime" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="TimeConstantPT1" type="xs:unsignedInt" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="VoltWattType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="xUnit" type="derUnitType"/>
			<xs:element name="yUnit" type="derUnitType"/>
			<xs:element name="CurveDataPoints" type="CurveDataPointsListType"/>
			<xs:element name="CurveDataPoints_L2" type="CurveDataPointsListType" minOccurs="0"/>
			<xs:element name="CurveDataPoints_L3" type="CurveDataPointsListType" minOccurs="0"/>
			<xs:element name="OpenLoopResponseTime" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="TimeConstantPT1" type="xs:unsignedInt" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CurveDataPointsListType">
		<xs:sequence>
			<xs:element name="CurveDataPoint" type="DataTupleType" minOccurs="2" maxOccurs="10"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DataTupleType">
		<xs:sequence>
			<xs:element name="xValue" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="yValue" type="v2gci_ct:RationalNumberType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="FrequencyDroop" type="FrequencyDroopType"/>
	<xs:complexType name="FrequencyDroopType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="OverFrequencyDroop" type="FrequencyDroopSettingsType" minOccurs="0"/>
			<xs:element name="UnderFrequencyDroop" type="FrequencyDroopSettingsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FrequencyDroopSettingsType">
		<xs:sequence>
			<xs:element name="db" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="DroopFactor" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="DroopFactor_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="DroopFactor_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="PowerReference" type="powerReferenceType"/>
			<xs:element name="PowerReference_L2" type="powerReferenceType" minOccurs="0"/>
			<xs:element name="PowerReference_L3" type="powerReferenceType" minOccurs="0"/>
			<xs:element name="OpenLoopResponseTime" type="v2gci_ct:RationalNumberType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="LimitMaxDischargePowerType">
		<xs:sequence>
			<xs:element name="Enable" type="xs:boolean"/>
			<xs:element name="Priority" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="PercentageValue" type="xs:unsignedShort"/>
			<xs:element name="PercentageValue_L2" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="PercentageValue_L3" type="xs:unsignedShort" minOccurs="0"/>
			<xs:element name="OpenLoopResponseTime" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVApparentPowerLimitsType">
		<xs:sequence>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarAbsorption" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarAbsorption_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarAbsorption_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarInjection" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarInjection_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarInjection_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarAbsorption" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarAbsorption_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarAbsorption_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarInjection" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarInjection_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarInjection_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVReactivePowerLimitsType">
		<xs:sequence>
			<xs:element name="EVMaximumVarAbsorptionDuringCharging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarAbsorptionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarAbsorptionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringCharging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringCharging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarInjectionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringCharging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarAbsorptionDuringDischarging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarAbsorptionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarAbsorptionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringDischarging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringDischarging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarInjectionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringDischarging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVReactiveSusceptance" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVReactiveSusceptance_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVReactiveSusceptance_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVExcitationLimitsType">
		<xs:sequence>
			<xs:element name="EVSpecifiedOverExcitedPowerFactor" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSpecifiedOverExcitedPowerFactor_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedOverExcitedPowerFactor_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedOverExcitedDischargePower" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSpecifiedOverExcitedDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedOverExcitedDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedPowerFactor" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSpecifiedUnderExcitedPowerFactor_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedPowerFactor_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedDischargePower" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSpecifiedUnderExcitedDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVInverterDetailsType">
		<xs:sequence>
			<xs:element name="EVInverterSwVersion" type="evInverterSwVersionType"/>
			<xs:element name="EVInverterHwVersion" type="evInverterHwVersionType" minOccurs="0"/>
			<xs:element name="EVInverterManufacturer" type="evInverterManufacturerType"/>
			<xs:element name="EVInverterModel" type="evInverterModelType"/>
			<xs:element name="EVInverterSerialNumber" type="evInverterSerialNumberType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVSEReactivePowerLimitsType">
		<xs:sequence>
			<xs:element name="EVSEMaximumVarAbsorptionDuringCharging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSEMaximumVarAbsorptionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSEMaximumVarAbsorptionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSEMaximumVarInjectionDuringCharging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSEMaximumVarInjectionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSEMaximumVarInjectionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSEMaximumVarAbsorptionDuringDischarging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSEMaximumVarAbsorptionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSEMaximumVarAbsorptionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSEMaximumVarInjectionDuringDischarging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSEMaximumVarInjectionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSEMaximumVarInjectionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GridLimitsType">
		<xs:sequence>
			<xs:element name="GridNominalFrequency" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="GridNominalVoltage" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="GridNominalVoltageOffset" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="GridMinFrequency" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="GridMaxFrequency" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="GridMaximumVoltage" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="GridMinimumVoltage" type="v2gci_ct:RationalNumberType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVApparentPowerType">
		<xs:sequence>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarAbsorption" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarAbsorption_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarAbsorption_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarInjection" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarInjection_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringChargingAndVarInjection_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarAbsorption" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarAbsorption_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarAbsorption_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarInjection" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarInjection_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumApparentPowerDuringDischargingAndVarInjection_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVReactivePowerType">
		<xs:sequence>
			<xs:element name="EVMaximumVarAbsorptionDuringCharging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarAbsorptionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarAbsorptionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringCharging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringCharging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarInjectionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringCharging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringCharging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringCharging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarAbsorptionDuringDischarging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarAbsorptionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarAbsorptionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringDischarging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarAbsorptionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringDischarging" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVMaximumVarInjectionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMaximumVarInjectionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringDischarging" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringDischarging_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVMinimumVarInjectionDuringDischarging_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EVExcitationType">
		<xs:sequence>
			<xs:element name="EVSpecifiedOverExcitedPowerFactor" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedOverExcitedPowerFactor_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedOverExcitedPowerFactor_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedOverExcitedDischargePower" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSpecifiedOverExcitedDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedOverExcitedDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedPowerFactor" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedPowerFactor_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedPowerFactor_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedDischargePower" type="v2gci_ct:RationalNumberType"/>
			<xs:element name="EVSpecifiedUnderExcitedDischargePower_L2" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
			<xs:element name="EVSpecifiedUnderExcitedDischargePower_L3" type="v2gci_ct:RationalNumberType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="derUnitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="V"/>
			<xs:enumeration value="Hz"/>
			<xs:enumeration value="W"/>
			<xs:enumeration value="s"/>
			<xs:enumeration value="var"/>
			<xs:enumeration value="PercentageEVMaximumConfiguredActivePower"/>
			<xs:enumeration value="PercentageEVMaximumConfiguredReactivePower"/>
			<xs:enumeration value="PercentageEVMaximumConfiguredApparentPower"/>
			<xs:enumeration value="PercentageEVMaximumAvailableActivePower"/>
			<xs:enumeration value="PercentageEVMaximumAvailableReactivePower"/>
			<xs:enumeration value="PercentageV"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ieee1547NormalCategoryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CategoryA"/>
			<xs:enumeration value="CategoryB"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ieee1547AbnormalCategoryType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CategoryI"/>
			<xs:enumeration value="CategoryII"/>
			<xs:enumeration value="CategoryIII"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="derOperationalStateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="On"/>
			<xs:enumeration value="Off"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="derConnectionStatusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Disconnected"/>
			<xs:enumeration value="Connected"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="powerFactorExcitationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OverExcited"/>
			<xs:enumeration value="UnderExcited"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="powerReferenceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MaximumActivePower"/>
			<xs:enumeration value="MomentaryPower"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="requiredDEROperatingModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GridFollowing"/>
			<xs:enumeration value="GridForming"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="gridConnectionModeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="GridConnected"/>
			<xs:enumeration value="GridIslanded"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="evInverterManufacturerType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="evInverterModelType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="evInverterSerialNumberType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="evInverterSwVersionType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="evInverterHwVersionType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="32"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>