<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <RootNamespace>cloud.charging.open.protocols.ISO15118</RootNamespace>
    <AssemblyName>Vanaheimr.V2G.Exi.Prototype</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WWCP_ISO15118_V2GTP\WWCP_ISO15118_V2GTP.csproj" />
    <AdditionalFiles Include="Schemas\V2G_CI_AppProtocol.xsd" />
    <ProjectReference Include="..\Vanaheimr.V2G.Exi.SourceGenerator\Vanaheimr.V2G.Exi.SourceGenerator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
