/*
 * Copyright (c) 2014-2025 GraphDefined GmbH <achim.friedland@graphdefined.com>
 * This file is part of WWCP ISO/IEC 15118 <https://github.com/OpenChargingCloud/WWCP_ISO15118>
 *
 * Licensed under the Affero GPL license, Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.gnu.org/licenses/agpl.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace cloud.charging.open.protocols.ISO15118.SLAC.Messages
{

    /// <summary>
    /// CM_SLAC_PARM.REQ: EV → EVSE (broadcast)
    /// </summary>
    /// <param name="RunId">The SLAC run ID, a random 8-byte value generated by the EV for each SLAC run.</param>
    /// <param name="ApplicationType">The SLAC application type. For EVSE matching, this MUST be set to 0x0001.</param>
    /// <param name="SecurityType">The SLAC security type. For EVSE matching, this MUST be set to 0x00 (no security).</param>
    public sealed record SLACParamReq(RunId  RunId,
                                      Byte   ApplicationType  = SLACConstants.ApplicationType_PevEvseMatching,
                                      Byte   SecurityType     = SLACConstants.SecurityType_None)

        : ISlacMessage

    {

        public ManagementMessageType MmType => ManagementMessageType.CM_SLAC_PARM_REQ;

        public Byte[] Encode()
        {

            var bytes = new Byte[1 + 1 + 8];
            bytes[0] = ApplicationType;
            bytes[1] = SecurityType;
            RunId.CopyTo(bytes.AsSpan(2, 8));

            return bytes;

        }

        public static SLACParamReq Decode(ReadOnlySpan<Byte> Bytes)
        {

            if (Bytes.Length < 10)
                throw new InvalidDataException("CM_SLAC_PARM.REQ truncated.");

            if (Bytes[0] != SLACConstants.ApplicationType_PevEvseMatching)
                throw new InvalidDataException($"CM_SLAC_PARM.REQ has unexpected ApplicationType '{Bytes[0]}'!");

            if (Bytes[1] != SLACConstants.SecurityType_None)
                throw new InvalidDataException($"CM_SLAC_PARM.REQ has unexpected SecurityType '{Bytes[1]}'!");

            var runId = new RunId(Bytes.Slice(2, 8));

            return new SLACParamReq(runId);

        }

    }

}
